before_script:
   - sudo apt-get install -y --force-yes git build-essential libsdl1.2-dev texinfo gawk chrpath diffstat qemu-system-arm libvirt0 libvirt-bin bridge-utils uml-utilities qemu-system-common
   - sudo easy_install tox
   - sudo easy_install pip
   # For Automated test below exports are done
   - export OPENBMC_HOST=$QEMU_IP
   - export OPENBMC_PASSWORD=0penBmc
   - export OPENBMC_USERNAME=root
   - export OPENBMC_MODEL=./data/Palmetto.py
   - export IPMI_COMMAND=External
   - export IPMI_PASSWORD=PASSW0RD
   
build_palmetto:
 stage: build
 script:
   - export TEMPLATECONF=meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/conf
   - . openbmc-env
   - bitbake obmc-phosphor-image
 artifacts:
   paths:
     - ./build/tmp/deploy/images/

build_ast2500:
 stage: build
 script:
  - export TEMPLATECONF=meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf
  - . openbmc-env
  - bitbake obmc-phosphor-image
 only: master
 artifacts:
  paths:
   - ./build/tmp/deploy/images/
  
build_firestone:
 stage: build
 script:
  - export TEMPLATECONF=meta-openbmc-machines/meta-openpower/meta-ibm/meta-firestone/conf
  - . openbmc-env
  - bitbake obmc-phosphor-image
 only: master
 artifacts:
  paths:
   - ./build/tmp/deploy/images/
   
test1:
 stage: test
 script: 
   - echo "Do a test here"
   - echo "For example run a test suite"
   
test2:
 stage: test
 script: 
   - echo "Do another parallel test here"
   - echo "For example run a lint test"
   
deploy1:
 stage: deploy
 script:
   - echo "Do your deploy here"