before_script:
   - sudo apt-get install -y git build-essential libsdl1.2-dev texinfo gawk chrpath diffstat
   - sudo easy_install tox
   - sudo easy_install pip
   - export OPENBMC_HOST=$QEMU_IP
   - export OPENBMC_PASSWORD=0penBmc
   - export OPENBMC_USERNAME=root
   - export OPENBMC_MODEL=./data/Palmetto.py
   - export IPMI_COMMAND=External
   - export IPMI_PASSWORD=PASSW0RD
   
build1:
 stage: build
 script:
   - cd openbmc
   - export TEMPLATECONF=meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/conf
   - . openbmc-env
   - bitbake obmc-phosphor-image

   
test1:
 stage: test
 script: 
   - echo "Do a test here"
   - echo "For example run a test suite"
   
test2:
 stage: test
 script: 
   - echo "Do another parallel test here"
   - echo "For example run a lint test"
   
deploy1:
 stage: deploy
 script:
   - echo "Do your deploy here"